#!/bin/bash
#
# check-new-code-coverage.sh
# 
# This script calculates code coverage for newly added/changed code in a PR.
# It uses git diff to identify changed files and extracts line coverage data
# from lcov.info (generated by cargo-llvm-cov). The script computes the
# average coverage percentage for changed lines only and compares it against
# a minimum threshold, exiting with code 0 if coverage is sufficient or 1 if not.
#
# Usage: ./check-new-code-coverage.sh [base_branch] [minimum_coverage_percent]
#   base_branch: Git base branch to diff against (default: origin/main)
#   minimum_coverage_percent: Minimum coverage threshold (default: 80)

set -euo pipefail

# Parse arguments with defaults
BASE_BRANCH="${1:-origin/main}"
MINIMUM_COVERAGE="${2:-80}"
LCOV_FILE="lcov.info"

# Check if we're in a GitHub Actions PR environment
if [[ -n "${GITHUB_EVENT_NAME:-}" && "$GITHUB_EVENT_NAME" != "pull_request" ]]; then
  echo "Not running in a pull_request event (github.event_name=$GITHUB_EVENT_NAME)"
  echo "Skipping new code coverage check"
  exit 0
fi

# Check if lcov.info exists
if [[ ! -f "$LCOV_FILE" ]]; then
  echo "Error: $LCOV_FILE not found in current directory"
  echo "Ensure coverage has been generated with cargo-llvm-cov before running this script"
  exit 1
fi

# Get changed files relative to base branch
echo "Checking for changed files against $BASE_BRANCH..."
CHANGED_FILES=$(git diff --name-only "$BASE_BRANCH"...HEAD 2>/dev/null || true)

if [[ -z "$CHANGED_FILES" ]]; then
  echo "No changed files found between $BASE_BRANCH and HEAD"
  echo "Assuming no new code to check - coverage check PASSED"
  exit 0
fi

echo "Changed files:"
echo "$CHANGED_FILES"
echo ""

# Filter for .rs files in src/ directory
CHANGED_RS_FILES=$(echo "$CHANGED_FILES" | grep -E '\.rs$' | grep '^src/' || true)

if [[ -z "$CHANGED_RS_FILES" ]]; then
  echo "No .rs files in src/ directory were changed"
  echo "Coverage check PASSED (no new code to check)"
  exit 0
fi

echo "Changed .rs files to check coverage:"
echo "$CHANGED_RS_FILES"
echo ""

# Track totals
TOTAL_EXECUTABLE_LINES=0
TOTAL_COVERED_LINES=0

# Function to extract line coverage for a specific file from lcov.info
# lcov.info format: SF:source_file
#                 DA:line_number,execution_count
extract_file_coverage() {
  local file="$1"
  
  # Normalize file path for lcov matching
  # lcov.info may contain paths like src/main.rs or /path/to/project/src/main.rs
  local file_pattern=$(echo "$file" | sed 's/\//\\\//g')
  
  # Extract DA lines for this file from lcov.info
  # Format: DA:line_number,hit_count (hit_count of 0 or >0 means line was executed)
  grep -A1000 "^SF:$file$" "$LCOV_FILE" 2>/dev/null | \
    grep "^DA:" | \
    while IFS=',' read -r prefix hit_count; do
      # Extract line number (remove DA: prefix)
      line_number="${prefix#DA:}"
      
      # Check if this line was changed in the diff
      if git diff "$BASE_BRANCH"...HEAD -- "$file" | grep -q "^+[^+].*$line_number"; then
        # Line was added - check if it's executable and covered
        if [[ "$hit_count" != "-" ]]; then
          TOTAL_EXECUTABLE_LINES=$((TOTAL_EXECUTABLE_LINES + 1))
          if [[ "$hit_count" -gt 0 ]] 2>/dev/null; then
            TOTAL_COVERED_LINES=$((TOTAL_COVERED_LINES + 1))
          fi
        fi
      fi
    done
}

# Alternative approach: Get exact changed line numbers per file
process_file_coverage() {
  local file="$1"
  
  # Get line numbers of added lines (lines starting with + but not ++)
  # Format: @@ -old_start,old_count +new_start,new_count @@ shows the diff hunk
  # We need to map the diff context to actual line numbers in the new file
  
  # Use git diff with line numbers to get changed lines
  local added_lines=$(git diff "$BASE_BRANCH"...HEAD -- "$file" --unified=0 2>/dev/null | \
    grep '^+' | \
    grep -v '^+++' | \
    sed 's/^+//')
  
  # For simplicity, we'll use git diff to get ranges and correlate with lcov
  # Get coverage data from lcov for this file
  local lcov_lines=$(grep -A10000 "^SF:$file$" "$LCOV_FILE" 2>/dev/null | grep "^DA:" | head -n -1 || true)
  
  if [[ -z "$lcov_lines" ]]; then
    # Try matching with relative path variations
    local basename=$(basename "$file")
    lcov_lines=$(grep -A10000 "^SF:.*$basename$" "$LCOV_FILE" 2>/dev/null | grep "^DA:" | head -n -1 || true)
  fi
  
  if [[ -z "$lcov_lines" ]]; then
    echo "  Warning: No coverage data found for $file"
    return
  fi
  
  # Get lines that were actually changed (not deletions)
  local changed_line_numbers=$(git diff "$BASE_BRANCH"...HEAD -- "$file" 2>/dev/null | \
    awk '
      /^@@/ { 
        # Parse hunk header: @@ -old_start,old_count +new_start,new_count @@
        match($0, /\+([0-9]+)(,([0-9]+))?/, parts)
        if (parts[3] != "") {
          new_start = parts[1]
          new_count = parts[3]
          for (i = 0; i < new_count; i++) {
            changed_lines[new_start + i] = 1
          }
        } else {
          changed_lines[parts[1]] = 1
        }
      }
      END {
        for (line in changed_lines) {
          print line
        }
      }
    ' | sort -n | uniq)
  
  if [[ -z "$changed_line_numbers" ]]; then
    echo "  No lines changed in $file"
    return
  fi
  
  # Process lcov DA lines for changed lines
  local file_executable=0
  local file_covered=0
  
  echo "$lcov_lines" | while IFS=',' read -r da_line hit_count; do
    line_number="${da_line#DA:}"
    
    # Check if this line was changed
    if echo "$changed_line_numbers" | grep -qx "$line_number"; then
      if [[ "$hit_count" != "-" ]]; then
        # This is an executable line (hit_count is a number, not "-")
        file_executable=$((file_executable + 1))
        if [[ "$hit_count" -gt 0 ]] 2>/dev/null; then
          file_covered=$((file_covered + 1))
        fi
      fi
    fi
  done
}

# Since bash subshells make variable tracking tricky, we'll use a different approach
# Write coverage data to a temporary file and process it
TEMP_FILE=$(mktemp)

echo "$CHANGED_RS_FILES" | while read -r file; do
  if [[ -z "$file" ]]; then continue; fi
  
  echo "Processing $file..."
  
  # Get changed line numbers
  changed_lines=$(git diff "$BASE_BRANCH"...HEAD -- "$file" 2>/dev/null | \
    awk '
      /^@@/ { 
        match($0, /\+([0-9]+)(,([0-9]+))?/, parts)
        if (parts[3] != "") {
          new_start = parts[1]
          new_count = parts[3]
          for (i = 0; i < new_count; i++) {
            changed_lines[new_start + i] = 1
          }
        } else {
          changed_lines[parts[1]] = 1
        }
      }
      END {
        for (line in changed_lines) {
          print line
        }
      }
    ' | sort -n | uniq)
  
  if [[ -z "$changed_lines" ]]; then
    echo "  No new lines in $file"
    continue
  fi
  
  # Find the matching SF record in lcov.info
  # Try exact path first
  lcov_data=$(awk -v file="$file" '
    BEGIN { in_file = 0 }
    /^SF:/ { 
      in_file = ($0 == "SF:" file)
    }
    in_file && /^DA:/ {
      print $0
    }
    /^end_of_record/ {
      in_file = 0
    }
  ' "$LCOV_FILE")
  
  # If no match, try basename matching
  if [[ -z "$lcov_data" ]]; then
    basename=$(basename "$file")
    lcov_data=$(awk -v basename="$basename" '
      BEGIN { in_file = 0 }
      /^SF:/ { 
        in_file = (index($0, basename) > 0)
      }
      in_file && /^DA:/ {
        print $0
      }
      /^end_of_record/ {
        in_file = 0
      }
    ' "$LCOV_FILE")
  fi
  
  if [[ -z "$lcov_data" ]]; then
    echo "  Warning: No coverage data found for $file"
    continue
  fi
  
  # Process each DA line for changed lines
  file_executable=0
  file_covered=0
  
  echo "$changed_lines" | while read -r line_num; do
    # Find this line in lcov data
    hit_count=$(echo "$lcov_data" | grep "^DA:$line_num," | cut -d',' -f2)
    
    if [[ -n "$hit_count" ]]; then
      if [[ "$hit_count" != "-" ]]; then
        file_executable=$((file_executable + 1))
        if [[ "$hit_count" -gt 0 ]] 2>/dev/null; then
          file_covered=$((file_covered + 1))
        fi
      fi
    fi
  done
  
  # Output totals for this file to temp file
  echo "$file_executable $file_covered" >> "$TEMP_FILE"
done

# Aggregate totals from all files
if [[ -f "$TEMP_FILE" && -s "$TEMP_FILE" ]]; then
  TOTAL_EXECUTABLE_LINES=$(awk '{sum += $1} END {print sum}' "$TEMP_FILE")
  TOTAL_COVERED_LINES=$(awk '{sum += $2} END {print sum}' "$TEMP_FILE")
  rm -f "$TEMP_FILE"
else
  rm -f "$TEMP_FILE"
  TOTAL_EXECUTABLE_LINES=0
  TOTAL_COVERED_LINES=0
fi

# Calculate coverage
if [[ "$TOTAL_EXECUTABLE_LINES" -eq 0 ]]; then
  echo "No executable lines found in changed code"
  echo "New code coverage: 100.00% (no executable code to check)"
  echo "PASS"
  exit 0
fi

COVERAGE_PERCENTAGE=$(awk "BEGIN {printf \"%.2f\", ($TOTAL_COVERED_LINES / $TOTAL_EXECUTABLE_LINES) * 100}")

echo ""
echo "Coverage Summary for Changed Code:"
echo "  Total executable lines changed: $TOTAL_EXECUTABLE_LINES"
echo "  Total covered lines changed: $TOTAL_COVERED_LINES"
echo "New code coverage: ${COVERAGE_PERCENTAGE}%"

# Compare against threshold
if awk "BEGIN {exit !($COVERAGE_PERCENTAGE >= $MINIMUM_COVERAGE)}"; then
  echo "PASS"
  exit 0
else
  echo "FAIL"
  echo "Required minimum coverage: ${MINIMUM_COVERAGE}%"
  exit 1
fi
